Resources:
  myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      ImageId: ami-051f8a213df8bc089
      Tags:
        - Key: Name
          Value: "change 3 amiid"


          