Parameters:
  keynameofinstance:
    Description: Name of the ec2 login key
    Type : AWS::EC2::KeyPair::KeyName
  NameOfService:
    Description : " The name of the service this stack is used for"
    Type : String
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

    
Mappings: 
  AmiRegionMap: 
    us-east-1: 
      "AMI": "ami-051f8a213df8bc089"
    us-east-2: 
      "AMI": "ami-0900fe555666598a2"
    us-west-1: 
      "AMI": "ami-0b990d3cfca306617"
    us-west-2: 
      "AMI": "ami-0395649fbe870727e"
Resources:
  myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName : !Ref keynameofinstance
      AvailabilityZone: us-east-1a
      ImageId: !FindInMap
         - AmiRegionMap
         - !Ref AWS::Region
         - AMI
      Tags:
        - Key: Name
          Value: !Ref NameOfService
      SecurityGroups:
         - !Ref vprofilesg

  vprofilesg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections from specified CIDR ranges my ip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 49.204.199.215/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 49.204.199.215/32