Resources:
  myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      ImageId: ami-07d9b9ddc6cd8dd30
      Tags:
        - Key: Name
          Value: !Join ["-",[my,instance,from,cloud,formation]]
      SecurityGroups:
         - !Ref vprofilesg

  
  vprofilesg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections from specified CIDR ranges my ip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 49.204.199.215/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 49.204.199.215/32