Resources:
  myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      ImageId: ami-07d9b9ddc6cd8dd30
      Tags:
        - Key: Name
          Value: !Join
             - " "
             - - "My instance in"
               - !Ref AWS::Region